### DISCUSSION TITLE
Setting eslint_dir

### DISCUSSION THREAD

**Discussion by jacobkellas** [wearerequired/lint-action#382] [Q&A] [answered]
I can't figure out where to include eslint_dir to set a subdirectory, do you have an example?  Thanks!

**Comment by ocean90** [comment, marked as answer]
`eslint_dir` is just another input for the action which you can set like this:

```yml
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_dir: path/to/custom/dir
```
