### DISCUSSION TITLE
Shall we support to cal `dotnet-format` global tool in some way?

### DISCUSSION THREAD

**Discussion by liny01-nbsa** [wearerequired/lint-action#457] [Q&A]
I want to use this with my legacy .Net Framework project. But I'm running into issue setting this action up.

As mentioned in this [documentation](https://github.com/dotnet/format):

> ![image](https://user-images.githubusercontent.com/38985073/165357390-864835cd-00b1-444f-a1b0-43dc4c564ff9.png)

I have tried to [fork and make a change](https://github.com/liny01-nbsa/lint-action/commit/08e69d0bb020c4beda3186241e4aa3f6e791d722) to the way linter is called, however, I run into issue:

![image](https://user-images.githubusercontent.com/38985073/165357878-c16c0717-29e4-481d-bf4c-05a4da286711.png)

But when I run the command directly it does work:

![image](https://user-images.githubusercontent.com/38985073/165358056-e0845287-3829-44b6-9a5c-c10c0efd4032.png)

I love the part your lint-action is able to capture the results and present it in a nice format. I would like to use this action directly.

Can dotnet-format call be supported directly?

**Comment by ocean90** [comment]
@ahanoff or @AndrewBabbitt97 can you help here?

**Reply by ahanoff** [reply]
```yml
name: Lint

on:
  - pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
        # Using specific version as recommended in https://github.com/dotnet/format/issues/1268#issuecomment-1047187839
        # latest .NET 6 SDK breaks built-in dotnet format
          dotnet-version: "6.0.102"

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          dotnet_format: true
          dotnet_format_dir: src
          auto_fix: true
          git_name: 'Lint Action'
          git_email: linter@example.com
          commit_message: 'fix: formatting with ${linter}'
```

@ocean90  I'm using this configuration. Works fine so far. I had to specify 6.0.102 though

**Reply by andrewbabbittdev** [reply]
@ahanoff Just a little note you can revert the dotnet version "6.0.102" now as it was fixed in https://github.com/dotnet/sdk/pull/24562 and made available in SDK version 6.0.202. This was an issue in several SDK versions over the past 2 months.

On the note of the topic at hand: The `dotnet tool install` command is no longer needed. As of .NET 6, its included in the SDK. I have submitted a PR to fix the docs to reflect this in #458

You should not be using `dotnet-format` and instead be using `dotnet format` as documented in the [tools repo](https://github.com/dotnet/format#how-to-use).

I have also tested .NET Format against .NET Framework and it works fine.

@liny01-nbsa The first image shows that an unknown parameter `--check` is being passed to the CLI, and this is indeed not a valid parameter in dotnet-format, see below:

```bash
$ dotnet format --help
Description:
  Formats code to match editorconfig settings.

Usage:
  dotnet-format [options] [<The project or solution file to operate on. If a file is not specified, the command will
  search the current directory for one.>] [command]

Arguments:
  <The project or solution file to operate on. If a file is   The project or solution file to operate on. If a file is
  not specified, the command will search the current          not specified, the command will search the current
  directory for one.>                                         directory for one. [default:
                                                              C:\Users\Personal\Desktop\lint-action\]

Options:
  --diagnostics <diagnostics>                              A space separated list of diagnostic ids to use as a filter
                                                           when fixing code style or 3rd party issues. [default: ]
  --severity <error|info|warn>                             The severity of diagnostics to fix. Allowed values are info,
                                                           warn, and error.
  --no-restore                                             Doesn't execute an implicit restore before formatting.
  --verify-no-changes                                      Verify no formatting changes would be performed. Terminates
                                                           with a non-zero exit code if any files would have been
                                                           formatted.
  --include <include>                                      A list of relative file or folder paths to include in
                                                           formatting. All files are formatted if empty. [default: ]
  --exclude <exclude>                                      A list of relative file or folder paths to exclude from
                                                           formatting. [default: ]
  --include-generated                                      Format files generated by the SDK.
  -v, --verbosity                                          Set the verbosity level. Allowed values are q[uiet],
  <d|detailed|diag|diagnostic|m|minimal|n|normal|q|quiet>  m[inimal], n[ormal], d[etailed], and diag[nostic]
  --binarylog <binary-log-path>                            Log all project or solution load information to a binary log
                                                           file.
  --report <report-path>                                   Accepts a file path which if provided will produce a json
                                                           report in the given directory.
  --version                                                Show version information
  -?, -h, --help                                           Show help and usage information

Commands:
  whitespace <The project or solution file to operate on.     Run whitespace formatting. [default:
  If a file is not specified, the command will search the     C:\Users\Personal\Desktop\lint-action\]
  current directory for one.>
  style <The project or solution file to operate on. If a     Run code style analyzers and apply fixes. [default:
  file is not specified, the command will search the          C:\Users\Personal\Desktop\lint-action\]
  current directory for one.>
  analyzers <The project or solution file to operate on. If   Run 3rd party analyzers and apply fixes. [default:
  a file is not specified, the command will search the        C:\Users\Personal\Desktop\lint-action\]
  current directory for one.>
```

So it looks like the issue is coming from additional args you are passing in the lint action options from what I can tell.

**Reply by liny01-nbsa** [reply]
*Do you think we can add a switch or parameter to support the case to use global `dotnet-format` as well if needed?*

**I'm working on legacy .Net Framekwork 4.8 code** not, .Net 6 code. I'm wondering if that could be the reason I'm having issue when I use the SDK 6 built-in `dotnet-format`.

Please see blow when I tried to use the lint-action directly. And I tried a few way, but I couldn't fix this issue.

![image](https://user-images.githubusercontent.com/38985073/165742890-68cf3a77-4598-4460-b800-dd532041e329.png)

@AndrewBabbitt97 I understand your explanation, and as you can see from above, I did try to use the action as-is, without success and using the global tool, `dotnet-format` would do the trick, though.

That's the reason I think I'm asking - Is it possible to choose the way dotnet-format is called by `dotnet format` (to use the SDK 6 built-in) or by `dotnet-format` to use the global tool.

As there's looks to be an difference, that could be the reason that's why there's the snippet shown in the official document I referenced.

> ![image](https://user-images.githubusercontent.com/38985073/165357390-864835cd-00b1-444f-a1b0-43dc4c564ff9.png)

**Reply by andrewbabbittdev** [reply]
@liny01-nbsa No need, the .NET 6 SDK works perfectly fine with .NET 4.8 projects. So you will still use the .NET 6 SDK.

I have set up a demo repo for you here: https://github.com/AndrewBabbitt97/lint-test

The repo has a .NET Framework 4.8 project, the same editorconfig as in the tests for the action itself, and a single github workflow that runs the linter.

Can find the workflow definition here: https://github.com/AndrewBabbitt97/lint-test/blob/main/.github/workflows/lint-code.yml

You will also find that the linter is working as expected: https://github.com/AndrewBabbitt97/lint-test/runs/6210214842?check_suite_focus=true

Maybe your workflow isnt setup correctlly? You are using Windows runners for the workflow correct? You cant use Linux runners even if its just for linting as dotnet format compiles the project in order to lint, so it will fail on linux.

So from my perspective, the action is working as intended and is fully compatible with .NET Framework 4.8.

**Reply by liny01-nbsa** [reply]
Thanks, @AndrewBabbitt97 , I will try to apply your approach in our repo, and report back.

**Reply by liny01-nbsa** [reply]
@AndrewBabbitt97 , I'm still running into the same error. (Of no error was detected :( )

And here is the run

![image](https://user-images.githubusercontent.com/38985073/165750041-4525c956-dff5-41a1-9b8d-897ef9dfb34c.png)

What exactly is 

> Warnings were encountered while loading the workspace. Set the verbosity option to the 'diagnostic' level to log warnings.
>  Required references did not load for NYKUBER or referenced project. Run `dotnet restore` prior to formatting.

My workflow file:
```yaml
name: dotnet-format check

on:
  push:
    branches:
      - master

jobs:
  format-check-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      ## This does work though

      # - name: Run dotnet-format
      #   run: |
      #     dotnet-format '.\NYKUber\' --folder --check --verbosity diagnostic

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          dotnet_format: true
          dotnet_format_dir: NYKUber/
          dotnet_format_extensions: cs
          dotnet_format_auto_fix: false
          # dotnet_format_args: '--folder --check --verbosity diagnostic'
          continue_on_error: true

```
