### DISCUSSION TITLE
Can seem to get action to work iwith flake8 plugin 'pyproject-flake8'

### DISCUSSION THREAD

**Discussion by jimisola** [wearerequired/lint-action#647] [General]
When running linting using this action flake8 configuration does not get picked up from pyproject.toml despite using installing flake8-pyprojec (see example below). Is there something else that needs to be done?

```

      - name: Install Python dependencies
        run: pip install black flake8 flake8-pyproject
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true

```
