### DISCUSSION TITLE
Annotations incorrectly linked to files or bad configuration?

### DISCUSSION THREAD

**Discussion by droodev** [wearerequired/lint-action#839] [Q&A]
This is how my configurations looks:
```
name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5https://github.com/science-for-democracy/mapof/runs/33058591708
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install black

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          black: true
          continue_on_error: false
 ```
 And after I do a test PR [(here link)](https://github.com/science-for-democracy/mapof/pull/3), the action correctly recognizes issues and builds an annotation
 
![image](https://github.com/user-attachments/assets/68b7d6a6-61c4-44c4-a83f-0f8a384b232b)

However, the link "see the allocation in the file changed" goes to a diff-view in where no annotation appears:
![image](https://github.com/user-attachments/assets/d86cb10a-bb63-4ed7-82ab-dd9aa44482b3)

Is it because the path of the annotated file starts with `/home/runner/`? Could you help me in configuring lint-action to actually see the annotations? I have tried some solutions (giving write permissions for pull-requests or playing with continue-on-error) but I'm stuck.
