### ISSUE TITLE
Error parsing ESLint JSON output: Unexpected end of JSON input. Output: ""

### ISSUE THREAD

**Issue by kosiakMD** [wearerequired/lint-action#185]
I tried to omit "custom" json files, but no

config
```
name: Lint
on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Check out Git branch name
        run: |
          chmod=+x .github/scripts/check_branch_naming.sh
          .github/scripts/check_branch_naming.sh
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
          eslint_args: "--config .eslintrc.js"
          
```

Extended Error Description:
```
Run wearerequired/lint-action@v1
  with:
    eslint: true
    prettier: true
    eslint_args: --config .eslintrc.js
    github_token: ***
    continue_on_error: true
    auto_fix: false
    git_name: Lint Action
    git_email: lint-action@samuelmeuli.com
    commit_message: Fix code style issues with ${linter}
    check_name: ${linter}
    stylelint: false
    stylelint_extensions: css,sass,scss
    gofmt: false
    gofmt_extensions: go
    golint: false
    golint_extensions: go
    eslint_extensions: js
    prettier_extensions: css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml
    xo: false
    xo_extensions: js
    php_codesniffer: false
    php_codesniffer_extensions: php
    black: false
    black_extensions: py
    flake8: false
    flake8_extensions: py
    mypy: false
    mypy_extensions: py
    rubocop: false
    rubocop_extensions: rb
    swiftformat: false
    swiftformat_extensions: swift
    swift_format_lockwood: false
    swift_format_lockwood_extensions: swift
    swift_format_official: false
    swift_format_official_extensions: swift
    swiftlint: false
    swiftlint_extensions: swift
SHA of last commit is "88543d18f758dbaaf0394cbfd2b7ee16264f273c"
Run ESLint
  Verifying setup for ESLint…
  Verified ESLint setup
  Will use ESLint to check the files with extensions js
  Linting files in /home/runner/work/***/*** with ESLint…
  
  Oops! Something went wrong! :(
  
  ESLint: 7.22.0
  
  You are linting ".", but all of the files matching the glob pattern "." are ignored.
  
  If you don't want to lint these files, remove the pattern "." from the list of arguments passed to ESLint.
  
  If you do want to lint these files, try the following solutions:
  
  * Check your .eslintignore file, or the eslintIgnore property in package.json, to ensure that the files are not configured to be ignored.
  * Explicitly list the files from this glob that you'd like to lint on the command-line, rather than providing a glob as an argument.
  
  Error: Error parsing ESLint JSON output: Unexpected end of JSON input. Output: ""
```
