### ISSUE TITLE
`git push` command fails in `push` workflow 

### ISSUE THREAD

**Issue by flmg** [wearerequired/lint-action#256]
Thanks for the action, it's super helpful 🙏 

With `auto_fix=true`, the `git push` command fails in the context of a `push` workflow because the remote url seems to only be set for `pull_request` https://github.com/wearerequired/lint-action/blob/970f3e9dc3c00ea468e489a17e41ffe9a629c618/src/index.js#L42

```
##[debug]Error: Command failed: git push
##[debug]fatal: could not read Username for 'https://github.com': No such device or address
```

As a workaround, I need to use `git remote set-url` before the action. Here's my workflow:

```yaml
name: Lint

on: push

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - uses: actions/setup-node@v2
              with:
                  node-version: '12'

            - run: npm config set unsafe-perm true && npm ci && git checkout .husky
            # This is needed for `git push` to work
            - run: git remote set-url origin https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
            - uses: wearerequired/lint-action@v1
              with:
                  commit_message: 'style: fix code style issues using ${linter}'
                  auto_fix: true
                  eslint: true
                  eslint_extensions: js,ts
                  prettier: true
```

Not a big issue on my side, but maybe this workaround can help people.

**Comment by ocean90** [comment]
Hey, thanks for the feedback. It's usually best practice to not trigger the `push` event for pull requests. And yeah, I just noticed that all the examples are also only using the `push` event. I think we should update them to use this syntax instead:

```yaml
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```

With that you wouldn't need to run the `git remote set-url` call by yourself.
