### ISSUE TITLE
Signing the commit(s)

### ISSUE THREAD

**Issue by vinayakkulkarni** [wearerequired/lint-action#259]
```yml
      - name: Run linter(s) 👀
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          continue_on_error: true
          git_name: github-actions[bot]
          git_email: github-actions[bot]@users.noreply.github.com
          auto_fix: true
          commit_message: "style: code style issues with ${linter}"
          stylelint: true
          eslint: true
          eslint_extensions: js,ts,vue
          prettier: true
          prettier_extensions: js,ts,vue
          neutral_check_on_warning: true
```

I want to ensure that the commit is signed:
<img width="846" alt="Screenshot 2021-06-15 at 7 03 26 PM" src="https://user-images.githubusercontent.com/19776877/122061688-61c28700-ce0c-11eb-82e4-994903f40c81.png">

This is the output of the above step
<img width="842" alt="Screenshot 2021-06-15 at 7 03 02 PM" src="https://user-images.githubusercontent.com/19776877/122061623-51aaa780-ce0c-11eb-8d32-7f9e2dfcff31.png">
