### ISSUE TITLE
Linting action added to a random workflow name

### ISSUE THREAD

**Issue by gvocale** [wearerequired/lint-action#280]
This is how my workflow looks:
```yml
name: Linters
on: push
jobs:
  run-linters:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          neutral_check_on_warning: true
          # Enable linters
          eslint: true
          eslint_args: "--max-warnings 0"
          prettier: true
```

After the workflow runs, I would expect to see ESLint and Prettier added to the checks, as in this screenshot taken from this repo readme:

![check-runs](https://user-images.githubusercontent.com/1319291/128428192-f44c77c9-5ada-4857-8f00-f11629e319f3.png)

Instead the checks are being somehow attached to Typescript, which is another workflow I have, looking like this:
```yml
name: Typescript
on: push
jobs:
  check-types:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
```

<img width="985" alt="Screen Shot 2021-08-05 at 6 13 03 PM" src="https://user-images.githubusercontent.com/1319291/128428209-14ac9793-3aa8-4b4e-8022-b541fe5c9066.png">

Somehow seems that the actions belongign to lint-action are attached to a random other workflow I have.

```
Storybook / ESLint
Storybook / Prettier
```

Instead should be:
```
ESLint
Prettier
```

Or alternatively:
```
Linters / ESLint
Linters / Prettier
```
