### ISSUE TITLE
Stylelint: When linting something other than CSS, you should install an appropriate syntax

### ISSUE THREAD

**Issue by rjensen26** [wearerequired/lint-action#352]
I am trying to run `Stylelint` but I am running into issues.
```
When linting something other than CSS, you should install an appropriate syntax.
```
I am using the following extensions:

```
extends:
  - stylelint-config-sass-guidelines
  - stylelint-config-prettier
```

Linting.yml

```
....
 - name: Check out Git repository
    uses: actions/checkout@v2

  - name: Set up Node.js
    uses: actions/setup-node@v1
    with:
      node-version: 14

  - name: Install Node.js dependencies
    run: npm ci

  - name: Run linters
    uses: wearerequired/lint-action@v1
    with:
      stylelint: true
      stylelint_command_prefix: npx
```
I also confirm that I do have the packages in my project because I can run: `npx stylelint` with no issues. I was wondering if anyone had an idea what might be causing this or did I miss something.

Thanks!
