### ISSUE TITLE
Error: Black is not installed

### ISSUE THREAD

**Issue by karstenzip** [wearerequired/lint-action#425]
Why do I get this error?
`Error: Black is not installed`
While it says `Successfully installed black-22.1.0 (and some more packages)` in `Install Python dependencies`
Here is the whole workflow:
```yml
name: Lint

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true
          flake8_args: "--ignore=E501,W503,F405"
          auto_fix: true
```
