### ISSUE TITLE
ERB Lint fails with not installed error

### ISSUE THREAD

**Issue by nickcharlton** [wearerequired/lint-action#495]
I'm trying out using this action on a project where we were already using `erblint` (originally on CircleCI as part of our build). I moved over to a single lint action, but unfortunately, I'm not able to run `erblint`:

```
Run wearerequired/lint-action@v2.0.1
SHA of last commit is "0e9d5bbff931342955546576f53368edfc1f4d6e"
Run ERB Lint
  Verifying setup for ERB Lint…
  /bin/sh: 1: erblint: not found
  Error: ERB Lint is not installed
```

```yaml
---
name: Lint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v3
      - name: Lint with StandardRB
        uses: testdouble/standard-ruby-action@v0.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint with other checks
        uses: wearerequired/lint-action@v2.0.1
        with:
          eslint: true
          erblint: true
```

Any thoughts on what I could try out here, or what might be wrong?
