### ISSUE TITLE
Unable to enable clang_format linter

### ISSUE THREAD

**Issue by ad3154** [wearerequired/lint-action#541]
With the following yml content, the clang_format linter is not recognized:

```
name: Lint

on: [push, pull_request]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
```
The following output is produced:

![image](https://user-images.githubusercontent.com/10929341/201442577-eb6e2ba8-06b8-499f-877e-9b7ba7b0600c.png)
