### ISSUE TITLE
Fails to create checkrun

### ISSUE THREAD

**Issue by fidalgodev** [wearerequired/lint-action#659]
![Screenshot 2023-06-10 at 01 50 39](https://github.com/wearerequired/lint-action/assets/41859298/ee2bc070-91dd-4993-bfa9-654cf2d63ac3)

```
name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          eslint_extensions: js,jsx,ts,tsx
          # prettier: true
          stylelint: true
          stylelint_extensions: css,scss

```

I keep getting a `403` error when it tries to create the check runs at the last step.
