### ISSUE TITLE
clang_format_auto_fix defaults to true or false?

### ISSUE THREAD

**Issue by sethkaz** [wearerequired/lint-action#782]
I'm implementing this action and using the clang_format linter.  I tried implementing it with only:
```
      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0
        with:
          clang_format: true
          auto_fix: true
```
However, I found that the auto-fix wasn't happening.  This seems counter to the README, which says that the `[linter]_auto_fix` defaults to `true` if the linter supports auto-fixing.  (I verified this by adding the line: `clang_format_auto_fix: true`, and it worked.)
